"type" = "green"
"constant" = "magenta"
"constant.numeric" = "light-red"
"constant.character.escape" = "yellow"
"string" = "cyan"
"string.regexp" = "light-cyan"
"comment" = "comments"
"variable" = "fg"
"variable.builtin" = "blue"
"variable.parameter" = "fg"
"variable.other.member" = "light-green"
"label" = "cyan"
"punctuation" = "comments"
"punctuation.delimiter" = "comments"
"punctuation.bracket" = "light-yellow"
"keyword" = "light-red"
"keyword.control" = "light-red"
"keyword.directive" = "light-red"
"keyword.storage" = "light-yellow"
"operator" = "light-yellow"
"function" = "blue"
"function.method" = "light-blue"
"function.builtin" = "blue"
"function.macro" = "magenta"
"tag" = "light-red"
"namespace" = "light-yellow"
"attribute" = "yellow"
"constructor" = "yellow"
"module" = "blue"
"special" = "light-magenta"

"markup.heading.marker" = "light-yellow"
"markup.heading.1" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.2" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.5" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.6" = { fg = "yellow", modifiers = ["bold"] }
"markup.list" = "light-red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "magenta"
"markup.quote" = "comments"
"markup.raw" = "magenta"

"diff.plus" = "diff_add"
"diff.delta" = "diff_mod"
"diff.minus" = "diff_del"

"ui.background" = { bg = "bg0" }
"ui.background.separator" = "bg1"
"ui.cursor" = { fg = "bg0", bg = "comments" }
"ui.cursor.match" = { fg = "black", bg = "yellow" }
"ui.cursor.insert" = { fg = "bg0", bg = "red" }
"ui.cursor.select" = { fg = "bg0", bg = "selection" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
"ui.selection" = { bg = "selection" }
"ui.linenr" = "comments"
"ui.linenr.selected" = "selection"
"ui.statusline" = { fg = "fg", bg = "bg1" }
"ui.statusline.inactive" = { fg = "bg1", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "fg", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "yellow", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "blue", modifiers = ["bold"] }
"ui.bufferline" = { fg = "bg1", bg = "bg1" }
"ui.bufferline.active" = { fg = "fg", bg = "bg1", modifiers = ["bold"] }
"ui.popup" = { fg = "bg1", bg = "bg1" }
"ui.window" = { fg = "bg1", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg1" }
"ui.text" = "fg"
"ui.text.focus" = "fg"
"ui.menu" = { fg = "fg", bg = "bg1" }
"ui.menu.selected" = { fg = "bg0", bg = "blue", modifiers = ["bold"]  }
"ui.virtual.whitespace" = { fg = "bg1" }
"ui.virtual.indent-guide" = { fg = "bg1" }
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.inlay-hint" = "comments"

"hint" = "blue"
"info" = "cyan"
"warning" = "yellow"
"error" = "red"
"diagnostic" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue", style = "dotted" } }
"diagnostic.info" = { underline = { color = "cyan", style = "dotted" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]
	fg = "#c7c7c7"
	bg0 = "#212121"
	bg1 = "#262626"

	comments = "#666666"

	line_numbers = "#424242"
	selection = "#404040"
	border = "#343434"
	highlight = "#8abeb7"

	warn = "#de935f"
	error = "#cc6666"

	black = "#282a2e"
	light-black = "#262626"
	white = "#c7c7c7"
	light-white = "#ffffff"
	red = "#a54242"
	light-red = "#cc6666"
	green = "#8c9440"
	light-green = "#b5bd68"
	blue = "#5f819d"
	light-blue = "#81a2be"
	yellow = "#de935f"
	light-yellow = "#ffeac3"
	magenta = "#85678f"
	light-magenta = "#b294bb"
	cyan = "#5e8d87"
	light-cyan = "#8abeb7"

	diff_add = "#4e5031"
	diff_mod = "#2e3f4d"
	diff_mod_text = "#43525e"
	diff_del = "#642828"

