"ui.background" = "white"
"ui.text" = "black"

[palette]

	fg = "#c7c7c7",
	bg = "#212121",

	comments = "#666666",

	line_numbers = "#424242",
	selection = "#404040",
	border = "#343434",
	highlight = "#8abeb7",

	none = "NONE",

	warn = "#de935f",
	error = "#cc6666",

	-- float colors
	float = "#262626",
	sidebar = "#262626",

	-- terminal colors
	black = "#282a2e",
	light-black = "#262626",
	white = "#c7c7c7",
	light-white = "#ffffff",
	red = "#a54242",
	light-red = "#cc6666",
	green = "#8c9440",
	light-green = "#b5bd68",
	blue = "#5f819d",
	light-blue = "#81a2be",
	yellow = "#de935f",
	light-yellow = "#ffeac3",
	magenta = "#85678f",
	light-magenta = "#b294bb",
	cyan = "#5e8d87",
	light-cyan = "#8abeb7",

	diff_add = "#4e5031",
	diff_mod = "#2e3f4d",
	diff_mod_text = "#43525e",
	diff_del = "#642828",
